### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by GavoTrav** [usandfriends/IRCLogger#1]
Error: Cannot find module 'moment'
Error: Cannot find module 'colors/safe'

You forgot to include them

**Comment by usandfriends** [comment]
You have to install them by running `npm install`.

**Comment by GavoTrav** [comment]
Yeah, Installed Moment, Colors, path, sprintf-js.

But It will not connect to a channel in quakenet irc.

**Comment by usandfriends** [comment]
See issue #2.
